### ISSUE TITLE
Unexpected error: could not translate element content for key

### ISSUE THREAD

**Issue by lisandi** [redhog/ep_embedmedia#10]
We receive the following Error Messages in Chrome on Mac OSX with the newest versions of Etherpad (installed yesterday from Github)

Unexpected error: could not translate element content for key ep_embedmedia.embed <a title=​"Embed Media" data-l10n-id=​"ep_embedmedia.embed" class=​"pressed">​…​</a>​flex

I submit the issue here because in the official repo is no issues enabled!

**Comment by JohnMcLear** [comment]
Confirmed

**Comment by JohnMcLear** [comment]
I'm rusty and can't find a fix for this within 15 mins of poking around, it's gotta be something really easy as referencing https://github.com/ether/ep_align everything is fine there..  :?
