### ISSUE TITLE
Clarify where to submit issues

### ISSUE THREAD

**Issue by slel** [redhog/ep_embedmedia#12]
The README says

> This repo has been moved to
> https://github.com/ether/ep_embedmedia

but the move seems incomplete as there is
no way to open an issue or a pull request there.

See discussion at
https://github.com/ether/etherpad-lite/issues/5192

Note that GitHub offers a way to move a repository
that transfers everything and adds a redirection
from the old repository and issue tracker to the new.
Maybe that should be explored and preferred to the
current situation where instead of such a move
the new repository seems to be a fork of the old.

**Comment by rhansen** [comment]
Issues have been enabled for the ether/ep_embededmedia project.

**Comment by JohnMcLear** [comment]
Thanks @rhansen 👍🏽

**Comment by slel** [comment]
Thanks.
