### ISSUE TITLE
Js error in FF and works in srWare Iron

### ISSUE THREAD

**Issue by quenenni** [redhog/ep_embedmedia#4]
- a video from youtube.

It works in srWare Iron, even if I have this error in the Js console:
<code>
Unsafe JavaScript attempt to access frame with URL http://xxxx:9001/p/haricots from frame with URL https://www.youtube.com/embed/Tcx6YyXvvRI. The frame requesting access has a protocol of 'https', the frame being accessed has a protocol of 'http'. Protocols must match.
</code>
But maybe it's because I access my etherpad in http and not https.

In FF (iceweasel), I can see the frame of the video, but it's a black static image.
In the Js console, I see:
<code>
ReferenceError: yt is not defined

yt.setConfig({
</code>
And these lines come from the script in https://www.youtube.com/embed/Tcx6YyXvvRI
- A video from vimeo

It works in srWare Iron, even if I have this error (different from youtube) in the Js console:
<code>
Unsafe JavaScript attempt to access frame with URL http:/xxxx.net:9001/p/haricots from frame with URL http://player.vimeo.com/video/62219238?color=ffffff. The frame being accessed set 'document.domain' to 'xxxx.net', but the frame requesting access did not. Both must set 'document.domain' to the same value to allow access.
</code>

In FF (iceweasel), same problem as for youtube. 
I can see the frame, but the video is not there.
<code>
ReferenceError: Player is not defined
....js"]},"mobile":{"css":["player.mobile.opt.css"],"js":["player.mobile.js"]},"des...
</code>
This Js error come from the script from the vimeo page (http://player.vimeo.com/video/62219238?color=ffffff)
- A video from dailymotion

The plugin doesn't work with these videos.
Is it in your TODO list? ;)

NB:
I don't have any problem to see videos from youtube or vimeo with my FF (iceweasel)

**Comment by JohnMcLear** [comment]
repo is at https://github.com/ether/ep_embedmedia
