### ISSUE TITLE
How to embed youtube video

### ISSUE THREAD

**Issue by vivekvt** [redhog/ep_embedmedia#8]
@JohnMcLear 
I have installed is plugin. But I don't know how to use this plugin.
In toolbar I can see small icon but pressing it nothing happens. I tried on both firefox and chrome.

![Screenshot from 2020-08-30 00-06-05](https://user-images.githubusercontent.com/50275510/91643876-a2efd300-ea54-11ea-9d23-ca3cb62107c6.png)

OS Ubuntu 18.04.5 LTS
Browser Firefox 79.0 (64-bit)
Browser Chrome 84.0.4147.125

**Comment by woeterman94** [comment]
Don't think this repo is still maintained...

**Comment by JohnMcLear** [comment]
repo is at https://github.com/ether/ep_embedmedia
