### ISSUE TITLE
Close and redirect to https://github.com/ether/ep_embedmedia

### ISSUE THREAD

**Issue by ovari** [redhog/ep_embedmedia#9]
Should this repository be closed and redirected to https://github.com/ether/ep_embedmedia ?

Thank you

**Comment by ovari** [comment]
https://github.com/redhog/ep_embedmedia/issues/7#issuecomment-775056143

**Comment by redhog** [comment]
Done

**Comment by JohnMcLear** [comment]
n1 ta
